import type { IRoleTableRow } from "./RoleTableRow.vue";

export const rolesData: IRoleTableRow[] = [
    {
        id: 1,
        roleName: "super-admin",
        displayName: "Super Administrator",
        description: "Full system access with all permissions",
        priority: 1,
        type: "system",
        status: "active",
        totalUsers: 2,
        createdAt: "2024-01-15",
    },
    {
        id: 2,
        roleName: "admin",
        displayName: "Administrator",
        description: "Administrative access to manage users and settings",
        priority: 2,
        type: "system",
        status: "active",
        totalUsers: 5,
        createdAt: "2024-01-15",
    },
    {
        id: 3,
        roleName: "manager",
        displayName: "Manager",
        description: "Manage team members and approve requests",
        priority: 3,
        type: "custom",
        status: "active",
        totalUsers: 12,
        createdAt: "2024-02-10",
    },
    {
        id: 4,
        roleName: "staff",
        displayName: "Staff",
        description: "Basic staff access to daily operations",
        priority: 4,
        type: "custom",
        status: "active",
        totalUsers: 45,
        createdAt: "2024-02-10",
    },
    {
        id: 5,
        roleName: "customer-service",
        displayName: "Customer Service",
        description: "Handle customer inquiries and support tickets",
        priority: 5,
        type: "custom",
        status: "active",
        totalUsers: 8,
        createdAt: "2024-03-05",
    },
    {
        id: 6,
        roleName: "content-creator",
        displayName: "Content Creator",
        description: "Create and manage content",
        priority: 6,
        type: "custom",
        status: "active",
        totalUsers: 6,
        createdAt: "2024-03-12",
    },
    {
        id: 7,
        roleName: "analyst",
        displayName: "Analyst",
        description: "View and analyze reports and data",
        priority: 7,
        type: "custom",
        status: "active",
        totalUsers: 4,
        createdAt: "2024-03-20",
    },
    {
        id: 8,
        roleName: "guest",
        displayName: "Guest",
        description: "Limited read-only access",
        priority: 10,
        type: "system",
        status: "inactive",
        totalUsers: 0,
        createdAt: "2024-01-15",
    },
];
