import type { IUserTableRow } from "./UserTableRow.vue";

export const usersData: IUserTableRow[] = [
    {
        id: 1,
        name: "Admin",
        email: "admin@admin.com",
        image: "/images/avatars/1.png",
        role: "Super Admin",
        status: "active",
        lastLogin: "1 hour ago",
    },
    {
        id: 2,
        name: "John Doe",
        email: "john.doe@example.com",
        image: "/images/avatars/2.png",
        role: "Admin",
        status: "active",
        lastLogin: "2 hours ago",
    },
    {
        id: 3,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        image: "/images/avatars/3.png",
        role: "Manager",
        status: "active",
        lastLogin: "3 hours ago",
    },
    {
        id: 4,
        name: "Michael Johnson",
        email: "michael.j@example.com",
        image: "/images/avatars/4.png",
        role: "Staff",
        status: "inactive",
        lastLogin: "2 days ago",
    },
    {
        id: 5,
        name: "Sarah Williams",
        email: "sarah.w@example.com",
        image: "/images/avatars/5.png",
        role: "Manager",
        status: "active",
        lastLogin: "5 hours ago",
    },
    {
        id: 6,
        name: "Robert Brown",
        email: "robert.b@example.com",
        image: "/images/avatars/6.png",
        role: "Staff",
        status: "active",
        lastLogin: "1 day ago",
    },
    {
        id: 7,
        name: "Emily Davis",
        email: "emily.d@example.com",
        image: "/images/avatars/7.png",
        role: "Admin",
        status: "active",
        lastLogin: "30 minutes ago",
    },
    {
        id: 8,
        name: "David Miller",
        email: "david.m@example.com",
        image: "/images/avatars/8.png",
        role: "Staff",
        status: "inactive",
        lastLogin: "5 days ago",
    },
    {
        id: 9,
        name: "Lisa Anderson",
        email: "lisa.a@example.com",
        image: "/images/avatars/9.png",
        role: "Manager",
        status: "active",
        lastLogin: "4 hours ago",
    },
    {
        id: 10,
        name: "Thomas Wilson",
        email: "thomas.w@example.com",
        image: "/images/avatars/10.png",
        role: "Staff",
        status: "active",
        lastLogin: "6 hours ago",
    },
];
